M48
; DRILL file KiCad 10.0.0 date 2026-04-06T23:45:47
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-06T23:45:47-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X45.185Y-64.36
X50.035Y-64.36
T2
X44.885Y-67.39
X50.335Y-67.39
T3
X23.4Y-47.96
X82.3Y-61.16
X87.4Y-30.46
M30
