apiVersion: v1
kind: Service
metadata:
  name: signald
  labels:
    {{- include "digits.signald.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "digits.signald.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.signald.port }}
      protocol: TCP
    - name: api
      port: {{ .Values.signald.port }}
      targetPort: {{ .Values.signald.port }}
      protocol: TCP
    {{- if .Values.observability.enabled }}
    - name: metrics
      port: {{ .Values.observability.signaldMetricsPort }}
      targetPort: {{ .Values.observability.signaldMetricsPort }}
      protocol: TCP
    {{- end }}
